# Generated by Django 5.0.6 on 2024-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
                ('fullness', models.IntegerField(default=40)),
                ('happiness', models.IntegerField(default=40)),
                ('is_sleeping', models.BooleanField(default=False)),
                ('avatar', models.CharField(default='images/neutral_cat.png', max_length=100)),
            ],
        ),
    ]
